### ISSUE TITLE
PHP Warning:  Only one @OA\Info() allowed for @OA\OpenApi() multiple found in

### ISSUE THREAD

**Issue by MattyRad** [DerManoMann/openapi-router#25]
Hi, ingenious library! Completely deduplicates and removes the need to define routes.

One issue is that it defines an Info attribute? I think here https://github.com/DerManoMann/openapi-router/blob/213be6ac94ac8c94d02c38e282fe5fadd55e02c2/src/OpenApiRouter.php#L206

I already have Info defined, as swagger-php [suggests it](https://zircote.github.io/swagger-php/guide/faq.html#warning-required-oa-info-not-found).

`PHP Warning:  Only one @OA\Info() allowed for @OA\OpenApi() multiple found in:` ... `vendor/radebatz/openapi-router/src/OpenApiRouter.php on line 209`

I'm not sure if there's an easy way to fix that short of finagling the autoloader.

**Comment by DerManoMann** [comment]
There is a config option `OPTION_OA_INFO_INJECT` to disable this.

Something like:
```php
$router = new OpenApiRouter(
    [__DIR__ . '/src'],
    new SlimRoutingAdapter($app),
    [OpenApiRouter::OPTION_OA_INFO_INJECT => false]
);
```

**Comment by MattyRad** [comment]
Ah, perfect. Thank you.
